enum site_args {
    UPDATE_DISPLAY,
    UPDATE_ACTION
}; 


static const int EFFECTS[] = {
    PA_PRINT,
    PA_SCAN_HORIZ,
    PA_SCROLL_LEFT,
    PA_WIPE,
    PA_SCROLL_UP_LEFT,
    PA_SCROLL_UP,
    PA_OPENING_CURSOR,
    PA_GROW_UP,
    PA_MESH,
    PA_SCROLL_UP_RIGHT,
    PA_BLINDS,
    PA_CLOSING,
    PA_RANDOM,
    PA_GROW_DOWN,
    PA_SCAN_VERT,
    PA_SCROLL_DOWN_LEFT,
    PA_WIPE_CURSOR,
    PA_DISSOLVE,
    PA_OPENING,
    PA_CLOSING_CURSOR,
    PA_SCROLL_DOWN_RIGHT,
    PA_SCROLL_RIGHT,
    PA_SLICE,
    PA_SCROLL_DOWN
};
